Umbraco-Gallery/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Umbraco_Gallery.ViewModels
{
    public class ContactViewModel
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name {get; set;}

        [Required(ErrorMessage = "Please enter your email address")]
        [EmailAddress(ErrorMessage = "You must enter a valid email address")]
        public string Email {get; set;}

        [Required(ErrorMessage = "Please enter your message")]
        [MaxLength(50, ErrorMessage = "Your message can't be longer than 500 characters")]
        public string Message {get; set;}

        public int ContactFormId {get; set;}
    }
}

Umbraco-Gallery/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Umbraco_Gallery.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Please enter your Username")]
        public string Username {get; set;}
        [Required(ErrorMessage = "Please enter your Password")]
        public string Password{get;set;}
    }
}

Umbraco-Gallery/Controllers/ContactSurfaceController.cs
using Umbraco.Web.Mvc;
using System.Web.Mvc;
using Umbraco_Gallery.ViewModels;
using Umbraco.Core.Models;
using NPoco.Expressions;
using Umbraco.Web;
using System.Web;
using System.Net.Mail;
using System;
using Umbraco.Core.Logging;
using Umbraco_Gallery.Services;

namespace Umbraco_Gallery.Controllers
{
    public class ContactSurfaceController : SurfaceController
    {
        private readonly ISmtpService _smtpService;
        public ContactSurfaceController(ISmtpService smtpService)
        {
            _smtpService = smtpService;
        }

        [HttpGet]
        public ActionResult RenderForm()
        {
            ContactViewModel model = new ContactViewModel() {ContactFormId = CurrentPage.Id};
            return PartialView("/Views/Partials/Contact/ContactForm.cshtml", model);
        }

        [HttpPost]
        public ActionResult RenderForm(ContactViewModel model)
        {
            return PartialView("/Views/Partials/Contact/ContactForm.cshtml", model);
        }

        public ActionResult SubmitForm(ContactViewModel model)
        {
            bool success = false;

            if (ModelState.IsValid)
            {
                success = _smtpService.SendEmail(model); 
            }

            var contactPage = UmbracoContext.Content.GetById(false, model.ContactFormId);
            var sucessMessage = contactPage.Value<IHtmlString>("successMessage");
            var errorMessage = contactPage.Value<IHtmlString>("errorMessage");

            return PartialView("/Views/Partials/Contact/result.cshtml", success ? sucessMessage : errorMessage);
        }
       
    }
}

Umbraco-Gallery/Controllers/MemberController.cs
using Umbraco_Gallery.ViewModels;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using Umbraco.Web;
using System.Web;

namespace Umbraco_Gallery.Controllers
{
    public class MemberController : SurfaceController
    {
        public ActionResult RenderLogin()
        {
            return PartialView("_Login", new LoginViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLogin(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                if(Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, false);
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError("", "The username or password is invalid");
                }
            }
            return CurrentUmbracoPage();
        }

        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToCurrentUmbracoPage();
        }
    }
}

Umbraco-Gallery/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.PublishedModels.About>
@using ClientDependency.Core.Mvc
@{
    Layout = "Master.cshtml";
}

@*Special header for the sub-pages*@
<header id="header">
    <div><span>@(Model.Root().Value<string>("title", fallback: Fallback.ToDefaultValue, defaultValue: Model.Name))</span></div>
</header>

<div class="inner">

    <header>
        <h1>@Model.Title</h1>
    </header>

    @Html.GetGridHtml(Model, "mainContent")
</div>

Umbraco-Gallery/Views/AccessDenied.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.AccessDenied>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "Master.cshtml";
}

<header id="header">
    <div><span>@(Model.Root().Value<string>("title", fallback: Fallback.ToDefaultValue, defaultValue: Model.Name))</span></div>
</header>

<div class="inner">

    <header>
        <h1>@Model.Title</h1>
    </header>
    <section>
        @Html.GetGridHtml(Model, "mainContent")
    </section>
    <a href="/register">Register</a>
    <a href="/login">Login</a>

</div>
<div class="fill-page" style="height:18em;"></div>

Umbraco-Gallery/Views/Gallery.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.PublishedModels.Gallery>
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Core.Services;
@using Umbraco.Core.PropertyEditors;

@{
    Layout = "Master.cshtml";
}

@*Special header for the sub-pages*@
<header id="header">
    <div><span>@(Model.Root().Value<string>("title", fallback: Fallback.ToDefaultValue, defaultValue: Model.Name))</span></div>
</header>

<!-- Gallery -->
<section id="galleries">

    <!-- Photo Galleries -->
    <div class="gallery">

        <!-- Filters -->
        <header>
            <h1>@Model.Title</h1>

            @{
                IDataTypeService dataTypeService = Services.DataTypeService;
                IDataType filterTags = dataTypeService.GetDataType(1144); // Change number to your id from the data types section in backoffice
                if (filterTags != null)
                {
                    ValueListConfiguration prevalues = (ValueListConfiguration)filterTags.Configuration;
                    <ul class="tabs">
                        <li><a href="#" data-tag="all" class="button active">All</a></li>
                        @foreach (ValueListConfiguration.ValueListItem item in prevalues.Items)
                        {
                            <li><a href="#" data-tag="@item.Value" class="button">@item.Value</a></li>
                        }
                    </ul>
                }
            }
        </header>

        @{
            var selection = Umbraco.Content(Guid.Parse("9f42fb70-2579-468f-b760-1559e78ea0d9"))
             .Children()
             .Where(x => x.IsVisible())
             .OrderByDescending(x => x.CreateDate);
        }

        <div class="content">
            @if (selection != null)
            {
                foreach (var item in selection)
                {
                    var image = item.Value<IPublishedContent>("mainImage");
                    var thumb = item.Value<IPublishedContent>("thumbnail");
                    var cssFilter = @item.Value("GalleryItemType");

                    <div class="media all @cssFilter">
                        <a href="@image.Url"><img src="@thumb.Url" alt="" title="@item.Name" /></a>
                    </div>
                }
            }
        </div>
    </div>
</section>

Umbraco-Gallery/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.PublishedModels.Home>
@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";
    var image = Model.Value<IPublishedContent>("mainImage");
}

<!-- Banner -->
<section id="banner" style="background-image: url(@image.Url);
">
    <div class="inner">
        <h1>@Model.Title</h1>
        <p>@Model.Subtitle</p>
        <ul class="actions">
            <li><a href="#gallery" class="button alt scrolly big">Continue</a></li>
        </ul>
        @{
            var myUser = Membership.GetUser();
            if (myUser != null)
            {
                <span class="home-screen-user"><icon class="fa fa-user" style="margin-right:.3em;"></icon>@myUser.UserName</span>
            }
        }
    </div>
</section>

<div class="inner">
    @Html.GetGridHtml(Model, "mainContent")
</div>

Umbraco-Gallery/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "Master.cshtml";
}

<header id="header">
    <div><span>@(Model.Root().Value<string>("title", fallback: Fallback.ToDefaultValue, defaultValue: Model.Name))</span></div>
</header>

<div class="inner">

    <header>
        <h1>@Model.Title</h1>
    </header>

    <section>
        @Html.GetGridHtml(Model, "mainContent")
    </section>
    @{
        Html.RenderAction("RenderLogin", "Member");
    }
    <p><a href="/register">Register a new account</a></p>
</div>

Umbraco-Gallery/Views/MacroPartials/ContactForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{Html.RenderAction("RenderForm", "ContactSurface"); }

Umbraco-Gallery/Views/MacroPartials/GalleryPreview.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
<!-- Gallery -->
@Html.Partial("/Views/Partials/_GalleryPreview.cshtml")

Umbraco-Gallery/Views/MacroPartials/GoogleMaps.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
<div style="display:flex; margin-bottom:1em;">
    <iframe style="display:flex;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3168.6365104529154!2d-122.08628374890367!3d37.4220655797262!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fba02425dad8f%3A0x6c296c66619367e0!2sGoogleplex!5e0!3m2!1ssv!2sse!4v1605269881299!5m2!1ssv!2sse" width="500" height="426" frameborder="0" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    <div style="display:flex; flex-direction:column; margin-left:1em; font-size:0.9em; font-weight:700; padding:1em; background:#fff;">
        <span>Phone</span>
        <p>142-0000-000</p>
        <span>Fax</span>
        <p>+1-212-9876543</p>
        <span>Email</span>
        <p>viewp@nomail.com</p>
    </div>
</div>

@*quick and dirty implementation, Keeping most of the values hardcoded for now*@

Umbraco-Gallery/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using ClientDependency.Core.Mvc
@{
    Layout = null;

    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js");
    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js");
    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js");
    Html.RequiresJs("/scripts/jquery.validate.min.js");
    Html.RequiresJs("/scripts/jquery.validate.unobtrusive.min.js");
    Html.RequiresJs("/scripts/jquery.unobtrusive-ajax.min.js");
    Html.RequiresJs("/scripts/cookiealert.js");

    Html.RequiresCss("/umbraco/assets/css/main.css");
    Html.RequiresCss("/umbraco/assets/css/cookiealert.css");

    Html.RequiresJs("/umbraco/assets/js/jquery.min.js");
    Html.RequiresJs("/umbraco/assets/js/jquery.poptrox.min.js");
    Html.RequiresJs("/umbraco/assets/js/jquery.scrolly.min.js");
    Html.RequiresJs("/umbraco/assets/js/skel.min.js");
    Html.RequiresJs("/umbraco/assets/js/util.js");
    Html.RequiresJs("/umbraco/assets/js/main.js");

    Html.RequiresJs("/scripts/contactForm.js");
}

<!DOCTYPE HTML>

<html>
<head>
    <title>@(Model.Value<string>("metaName"))</title>
    <meta name="description" content="@(Model.Value<string>("metaDescription"))" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    @Html.RenderCssHere()

</head>
<body>
    <div class="page-wrap">

        @Html.Partial("/Views/Partials/_Navigation.cshtml")

        <section id="main">

            @RenderBody()


            @Html.Partial("/Views/Partials/_Footer.cshtml")

        </section>
    </div>
    <div class="cookiealert" role="alert">
        <div class="cookiealert-container">
            <b>Do you like cookies?</b> &#x1F36A; We use cookies to ensure you get the best experience on our website. <a href="http://cookiesandyou.com/" target="_blank">Learn more</a>
            <br/>
            <button type="button" class="btn btn-primary btn-sm acceptcookies" aria-label="Close">
                I agree
            </button>
        </div>
    </div>
    @Html.RenderJsHere()
</body>
</html>

Umbraco-Gallery/Views/MembersOnly.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.MembersOnly>
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Core.Services;
@using Umbraco.Core.PropertyEditors;
@{
    Layout = "Master.cshtml";
}

@*Special header for the sub-pages*@
<header id="header">
    <div><span>@(Model.Root().Value<string>("title", fallback: Fallback.ToDefaultValue, defaultValue: Model.Name))</span></div>
</header>

<!-- Gallery -->
<section id="galleries">

    <!-- Photo Galleries -->
    <div class="gallery">

        <!-- Filters -->
        <header>
            <h1>@Model.Title</h1>
            @{
                IDataTypeService dataTypeService = Services.DataTypeService;
                IDataType filterTags = dataTypeService.GetDataType(1208); // Change number to your id from the data types section in backoffice
                if (filterTags != null)
                {
                    ValueListConfiguration prevalues = (ValueListConfiguration)filterTags.Configuration;
                    <ul class="tabs">
                        <li><a href="#" data-tag="all" class="button active">All</a></li>
                        @foreach (ValueListConfiguration.ValueListItem item in prevalues.Items)
                        {
                            <li><a href="#" data-tag="@item.Value" class="button">@item.Value</a></li>
                        }
                    </ul>
                }
            }
        </header>

        @{
            var selection = Umbraco.Content(Guid.Parse("0e984227-d526-465c-aaa7-390f89d6fa17"))
              .Children()
              .Where(x => x.IsVisible())
              .OrderByDescending(x => x.CreateDate);
        }

        <div class="content">
            @if (selection != null)
            {
                foreach (var item in selection)
                {
                    var image = item.Value<IPublishedContent>("mainImage");
                    var thumb = item.Value<IPublishedContent>("thumbnail");
                    var cssFilter = @item.Value("mOItemType");

                    <div class="media all @cssFilter">
                        <a href="@image.Url"><img src="@thumb.Url" alt="" title="@item.Name" /></a>
                    </div>
                }
            }
        </div>
    </div>
</section>

Umbraco-Gallery/Views/Partials/BlockList/Default.cshtml
@inherits UmbracoViewPage<BlockListModel>
@using Umbraco.Core.Models.Blocks
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;
        @Html.Partial("BlockList/Components/" + data.ContentType.Alias, block)        
    }
</div>

Umbraco-Gallery/Views/Partials/Contact/contactForm.cshtml
@inherits UmbracoViewPage<Umbraco_Gallery.ViewModels.ContactViewModel>
@using Umbraco_Gallery.Controllers


@using (Ajax.BeginForm("SubmitForm", "ContactSurface", new AjaxOptions()
{
    UpdateTargetId = "form-result",
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "contactForm.showResult",
    OnFailure = "contactForm.showResult"
}, new { id = "contact-form" }))
{

    @Html.HiddenFor(m => m.ContactFormId)

    <div class="field half first">
        <label for="name">Name</label>
        @Html.ValidationMessageFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })

    </div>
    <div class="field half">
        <label for="email">Email</label>
        @Html.ValidationMessageFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
    </div>
    <div class="field">
        <label for="message">Message</label>
        @Html.ValidationMessageFor(m => m.Message)
        @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Message", rows = "6" })
    </div>
    <ul class="actions">
        <li><input value="Send Message" class="button contact-submit" type="submit"></li>
    </ul>
}
<div id="form-result"></div>

Umbraco-Gallery/Views/Partials/Contact/result.cshtml
@model IHtmlString
@Model

Umbraco-Gallery/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@*
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row)
                    }
                </div>
            }
        }else {
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row)
                            }
                        </div>
                    </div>
                }
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Umbraco-Gallery/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true)
                    }
                </div>
            }
        }else {
     
                    foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false)
                                }
                            </div>
                        </div>
                    }
         
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @if (singleColumn) {

        }
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        @if (singleColumn) {
        }
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Umbraco-Gallery/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Umbraco-Gallery/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@{
    string embedValue = Convert.ToString(Model.value);
    embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;
}

<div class="video-wrapper">
	@Html.Raw(embedValue)
</div>

Umbraco-Gallery/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Umbraco-Gallery/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Core.PropertyEditors.ValueConverters

@if (Model.value != null)
{
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        if (Model.value.coordinates != null)
        {
            url = ImageCropperTemplateExtensions.GetCropUrl(
                (string)url,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropAlias: "default",
                cropDataSet: new ImageCropperValue
                {
                    Crops = new[]
                    {
                        new ImageCropperValue.ImageCropperCrop
                        {
                            Alias = "default",
                            Coordinates = new ImageCropperValue.ImageCropperCropCoordinates
                            {
                                X1 = (decimal)Model.value.coordinates.x1,
                                Y1 = (decimal)Model.value.coordinates.y1,
                                X2 = (decimal)Model.value.coordinates.x2,
                                Y2 = (decimal)Model.value.coordinates.y2
                            }
                        }
                    }
                });
        }
        else
        {
            url = ImageCropperTemplateExtensions.GetCropUrl(
                (string)url,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropDataSet: new ImageCropperValue
                {
                    FocalPoint = new ImageCropperValue.ImageCropperFocalPoint
                    {
                        Top = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.top,
                        Left = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.left
                    }
                });
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;

    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Umbraco-Gallery/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates
@{
    var value = TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider);
    value = TemplateUtilities.ResolveUrlsFromTextString(value);
    value = TemplateUtilities.ResolveMediaFromTextString(value);
}
@Html.Raw(value)

Umbraco-Gallery/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode((string)Model.value.ToString())).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

Umbraco-Gallery/Views/Partials/_Footer.cshtml
@using Umbraco.Web.Models
@inherits UmbracoViewPage

@{
    var homePage = Model.AncestorOrSelf<Home>();
    var socialLinks = homePage.Value<IEnumerable<IPublishedElement>>("socialLinks");
}
<!-- Footer -->
<footer id="footer">
    <div class="copyright">
        @if (socialLinks != null && socialLinks.Any())
        {
            <ul class="icons">
                @foreach (var item in socialLinks)
                {
                    var link = item.Value<Link>("link");
                    var iconCLass = item.Value<string>("iconClass");
                    <li><a href="@link.Url" target="@link.Target" class="@iconCLass"><span class="label">Twitter</span></a></li>
                }
            </ul>
        }
        else
        {
            <ul class="icons">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
            </ul>
        }

        &copy; @Umbraco.GetDictionaryValue("Footer.CopyrightName") | Design: <a href="https://templated.co/" target="_blank">TEMPLATED</a>. Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a>.
    </div>
</footer>